### ISSUE TITLE
using redshift pool .. This socket has been ended by the other party

### ISSUE THREAD

**Issue by windjay** [dmanjunath/node-redshift#8]
var redshift_info = {
    user: 'dsi',
    database: 'id...',
    password: 'pass',
    port: '5439',
    host: 'aws.xxxxxx.com,
    max: 10, // max number of clients in the pool
    idleTimeoutMillis: 5000,
};
var redshiftClient = new redshift(redshift_info, {rawConnection: false});

and insert some data to redshift ..
at first insert ok... some data insert to redshift
but after that 
i got below error

2017-01-17 01:59:25 - error:  Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:291:12)
    at Connection.query (/app/node-server/node_modules/pg/lib/connection.js:204:15)
    at Query.submit (/app/node-server/node_modules/pg/lib/query.js:138:16)
    at Client._pulseQueryQueue (/app/node-server/node_modules/pg/lib/client.js:307:24)
    at Client.query (/app/node-server/node_modules/pg/lib/client.js:335:8)
    at runQuery (/app/node-server/node_modules/node-redshift/lib/query.js:37:15)
    at Redshift.query (/app/node-server/node_modules/node-redshift/lib/query.js:33:8)

**Comment by dmanjunath** [comment]
@windjay Every now and them redshift takes all your connections down during the maintanance window. Can you verify that Amazon wasn't doing maintenance? You can find out by looking here in the AWS Redshift status page

![redshift_ _aws_console](https://cloud.githubusercontent.com/assets/295938/22005990/a3674de4-dc35-11e6-987d-39c1aa86d9a8.png)

**Comment by schmidp** [comment]
Might be related to: https://github.com/dmanjunath/node-redshift/pull/10

**Comment by dmanjunath** [comment]
Merged and published

**Comment by neilpalima** [comment]
@dmanjunath how can I set max and min connection pools? Is this possible? Putting `max` does not seem to work on my end.
